// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCSphTgCQkg-2ewV4fIsllv-X83hbeg8M',
    appId: '1:577112171949:web:b2c80c0dc388a9766b6d24',
    messagingSenderId: '577112171949',
    projectId: 'delivoriaapp',
    authDomain: 'delivoriaapp.firebaseapp.com',
    storageBucket: 'delivoriaapp.firebasestorage.app',
    measurementId: 'G-VGFVEGQRLD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwNwcin15bfJ4_vZGao0Eyv4M3waXLwS0',
    appId: '1:577112171949:android:9a2775f58e95bb936b6d24',
    messagingSenderId: '577112171949',
    projectId: 'delivoriaapp',
    storageBucket: 'delivoriaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPGxLg4klRvGGqCVRiTICw6CFredy0Glw',
    appId: '1:577112171949:ios:12abff65dee578906b6d24',
    messagingSenderId: '577112171949',
    projectId: 'delivoriaapp',
    storageBucket: 'delivoriaapp.firebasestorage.app',
    iosBundleId: 'com.example.delivoria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPGxLg4klRvGGqCVRiTICw6CFredy0Glw',
    appId: '1:577112171949:ios:12abff65dee578906b6d24',
    messagingSenderId: '577112171949',
    projectId: 'delivoriaapp',
    storageBucket: 'delivoriaapp.firebasestorage.app',
    iosBundleId: 'com.example.delivoria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCSphTgCQkg-2ewV4fIsllv-X83hbeg8M',
    appId: '1:577112171949:web:c5dabc27596e46e96b6d24',
    messagingSenderId: '577112171949',
    projectId: 'delivoriaapp',
    authDomain: 'delivoriaapp.firebaseapp.com',
    storageBucket: 'delivoriaapp.firebasestorage.app',
    measurementId: 'G-FH3B7JPNLD',
  );
}
